{
 "title": "Vulture : Report / Security",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "elasticsearch", "query": "elasticsearch" },
   {
    "name": "Browser",
    "label": "browser",
    "query": "{\"find\": \"terms\", \"field\": \"user_agent.keyword\", \"size\": 1000}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: #FFFFFF; background-color: #39a5ee; font-size: 17px;\">\n<img src=\"https://raw.githubusercontent.com/VultureProject/vulture3-gui/master/gui/static/img/vulture_logo.png\" width: 100% height: auto; >\n</h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of hits by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:396",
       "fake": true,
       "field": "http_code",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:265",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:263",
       "field": "direction.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:vulture-access",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average score by status code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3649",
       "fake": true,
       "field": "http_code",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "6", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3206",
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3640",
       "field": "score",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_type:vulture-access",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Distribution of blocked requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3649",
       "fake": true,
       "field": "reasons.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3206",
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3640",
       "field": "src_ip.keyword",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:vulture-access NOT reasons.keyword:\"-\" NOT reasons.keyword:\"[]\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of blocked requests",
   "type": "graph",
   "description": "by attack category",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:560",
       "fake": true,
       "field": "reasons.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "4" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3206",
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3640",
       "field": "score",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:vulture-access NOT reasons.keyword:\"-\" NOT reasons.keyword:\"[]\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Reputation tags",
   "type": "grafana-piechart-panel",
   "description": "hits per tag",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3649",
       "fake": true,
       "field": "reputation.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3206",
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3640",
       "field": "src_ip.keyword",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:vulture-access NOT reputation.keyword:\"-,-,-,-,-\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IP list reputation for abuse tag",
   "type": "graph",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:560",
       "fake": true,
       "field": "src_ip.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "4" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3649",
       "fake": true,
       "field": "reputation.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "4" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:3206",
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3640",
       "field": "score",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "_type:vulture-access NOT reputation.keyword:\"-,-,-,-,-\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}